### ISSUE TITLE
Any way to make menu entry icons smaller?

### ISSUE THREAD

**Issue by ardevd** [lukechilds/refind-ambience#1]
So I am currently using refind on a system with a single OS. With your theme that one icon for the OS is huge to the point where the icon resolution is insufficient for displaying a crisp icon image. Is there any way to reduce the menu entry icon sizes?

**Comment by lukechilds** [comment]
Somebody else mentioned about large icon sizes, I think it may be due to the fact that it was designed for my retina MacBook Pro, I haven't actually tested on other resolutions.

Could you provide me with a screenshot? Pressing F10 in rEFInd will save a screenshot to the top level directory of the ESP.

**Comment by lukechilds** [comment]
@Zyg0te It'd be awesome if you could get me that screenshot. My MacBook Pro only supports one EFI video mode so I can't boot it in 1080p.

I'd really like to get this working for people of all screen resolutions.

**Comment by ardevd** [comment]
Hey, apologies for the late response. I'll try to get that screenshot to you tomorrow. 

Cheers

**Comment by lukechilds** [comment]
Thanks, appreciate it 👍

**Comment by ardevd** [comment]
F10 didnt seem to generate any screenshots. Any ideas?

**Comment by lukechilds** [comment]
Did you check the root of your EFI partition for the screenshots? (not the rEFInd root)

Failing that, snap a pic on your phone?

**Comment by lukechilds** [comment]
Also, what resolution are you running?

**Comment by ardevd** [comment]
Resolution: 1920x1200

**Comment by lukechilds** [comment]
I've just added a new branch called [`low-dpi`](https://github.com/lukechilds/refind-ambience/tree/low-dpi). Can you try checking that out and seeing if it looks better for you?

If it does I'll add two separate dpi configs to the main branch.

**Comment by lukechilds** [comment]
Also, do you know what resolution rEFInd is using? Have you set one in your config? It may be that your machine is using a really low resolution video mode for EFI.

**Comment by lukechilds** [comment]
@Zyg0te Sorry to pester, did you get a chance to try that branch out?

**Comment by ardevd** [comment]
Hey! Apologies for the late response. I did a bit of testing. I tried a different theme and I experienced the same issue. Turns out it was simply a matter of my resolution settings being bugged and I kinda... tricked myself into thinking your theme was the issue. Everything works fine now! Apologies for the trouble

**Comment by lukechilds** [comment]
@Zyg0te No problem, glad you got it sorted 👍

**Comment by jakiisheep** [comment]
I fixed this by changing the ```refind.conf``` resolution setting to ```max```.
