### ISSUE TITLE
MOK Utility access

### ISSUE THREAD

**Issue by ardevd** [lukechilds/refind-ambience#2]
Hello again.

Is there some sort of magic key combination needed to access the MOK utility? I have secure boot enabled and I need to re-enroll my kernel every time it's upgraded. Using your theme I cant seem to access the MOK utility so I end up disabling secure boot, disabling the theme, enrolling the kernel hash, before enabling secure boot and your theme again.

Thank you.

**Comment by lukechilds** [comment]
@Zyg0te There is a `showtools` parameter in the rEFInd config to set which tools should be visible. I wanted my theme to be super minimal so I just hid the controls and I haven't created any icons for them.

You can enable them again by adding your own `showtools` setting **after** the theme include in your config.

Search for `showtools` on this page for more info: http://www.rodsbooks.com/refind/configfile.html

It'll just fallback to the default rEFInd icons so it'll look pretty ugly. I'll create an issue for adding some proper icons.
